### ISSUE TITLE
Christine's to-do list

### ISSUE THREAD

**Issue by chrisbean** [chrisbean/Mastering_GitHub#1]
### Needs
- [x] Fewer blocks; treat them like H1s or slides, components for subhead 
- [x] Look into how the borders are coded around menu blocks on landing page. can that be applied to LOs component?
- [x] could I hackily use some inline CSS to add a color screen bkgd???
- [x] Determine how/where to publish/share: (https://www.linkedin.com/pulse/create-responsive-learning-rapidly-adapts-free-tool-milloway-msit)
- [x] renumber components 
- [x] Rework landing page; COs should be intro blurbs not TOCs
- [x] In README: ref Polaris and burst
- [x] Move running asks and to dos to issues

### Enhancements/nice-to-haves
- [x] Install a nav link component

**Comment by chrisbean** [comment]
### M1L1
- [ ] Swap in a “matching” quiz element for “accordion” to handle definitions of key terms
- [ ] Add an outro / summary at end of lesson

**Comment by chrisbean** [comment]
updated

**Comment by chrisbean** [comment]
@kacres I force-pushed the complete contents of **src** folder to repo, which should eliminate the manual workaround we needed to do on 9/30.

**Comment by kacres** [comment]
> ### M1L1
> * [ ]  Swap in a “matching” quiz element for “accordion” to handle definitions of key terms (eg. [Dan Storey's drag-and-drop](https://github.com/danielstorey/adapt-draganddrop))

Since the drag-and-drop plug-in is not part of the core offering of adapt, it may not be as easy to install. If that is the case, you could likely use the [adapt-contrib-matching](https://github.com/adaptlearning/adapt-contrib-matching/wiki) plug-in
